### ISSUE TITLE
questions about resolution

### ISSUE THREAD

**Issue by wuzhi19931128** [kyegomez/PALI3#5]
In the article,  larger resolution is used for downstream tasks, but only 224-resolution pictures are used in demo.I have some questions about this:
1. Does the resolution of different pictures have a great influence on the model effect?
2. How to transform a low-resolution model into a high-resolution model as an initialization model？
3. The number of  model parametersare lower than other multimodel models, but the resolution is much higher. Is it unfair to compare the results of the same parameters models?

**Comment by kyegomez** [comment]
@wuzhi19931128 

- Better resolution => better model
- You just increase the resolution
- Yes, do not compare results with a high res model to low res
